version: "3"

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: docker_db
    volumes:
      - .mysql:/var/lib/mysql
    ports:
      - 3306:3306

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - .docker/php-fpm/php.ini:/etc/php/7.2/fpm/conf.d/40-custom.ini
      - .:/var/www

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - .docker/nginx/nginx.cnf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
